// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v6.33.2
// source: signaling/signaling.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// SignalingServiceClient is the client API for SignalingService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SignalingServiceClient interface {
	DecideRequest(ctx context.Context, in *SpaceMember, opts ...grpc.CallOption) (*Void, error)
	BroadcastToLobby(ctx context.Context, in *BroadcastRequest, opts ...grpc.CallOption) (*Void, error)
	Unicast(ctx context.Context, in *UnicastRequest, opts ...grpc.CallOption) (*Void, error)
}

type signalingServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSignalingServiceClient(cc grpc.ClientConnInterface) SignalingServiceClient {
	return &signalingServiceClient{cc}
}

func (c *signalingServiceClient) DecideRequest(ctx context.Context, in *SpaceMember, opts ...grpc.CallOption) (*Void, error) {
	out := new(Void)
	err := c.cc.Invoke(ctx, "/signaling.SignalingService/DecideRequest", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *signalingServiceClient) BroadcastToLobby(ctx context.Context, in *BroadcastRequest, opts ...grpc.CallOption) (*Void, error) {
	out := new(Void)
	err := c.cc.Invoke(ctx, "/signaling.SignalingService/BroadcastToLobby", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *signalingServiceClient) Unicast(ctx context.Context, in *UnicastRequest, opts ...grpc.CallOption) (*Void, error) {
	out := new(Void)
	err := c.cc.Invoke(ctx, "/signaling.SignalingService/Unicast", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SignalingServiceServer is the server API for SignalingService service.
// All implementations must embed UnimplementedSignalingServiceServer
// for forward compatibility
type SignalingServiceServer interface {
	DecideRequest(context.Context, *SpaceMember) (*Void, error)
	BroadcastToLobby(context.Context, *BroadcastRequest) (*Void, error)
	Unicast(context.Context, *UnicastRequest) (*Void, error)
	mustEmbedUnimplementedSignalingServiceServer()
}

// UnimplementedSignalingServiceServer must be embedded to have forward compatible implementations.
type UnimplementedSignalingServiceServer struct {
}

func (UnimplementedSignalingServiceServer) DecideRequest(context.Context, *SpaceMember) (*Void, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DecideRequest not implemented")
}
func (UnimplementedSignalingServiceServer) BroadcastToLobby(context.Context, *BroadcastRequest) (*Void, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BroadcastToLobby not implemented")
}
func (UnimplementedSignalingServiceServer) Unicast(context.Context, *UnicastRequest) (*Void, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Unicast not implemented")
}
func (UnimplementedSignalingServiceServer) mustEmbedUnimplementedSignalingServiceServer() {}

// UnsafeSignalingServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SignalingServiceServer will
// result in compilation errors.
type UnsafeSignalingServiceServer interface {
	mustEmbedUnimplementedSignalingServiceServer()
}

func RegisterSignalingServiceServer(s grpc.ServiceRegistrar, srv SignalingServiceServer) {
	s.RegisterService(&SignalingService_ServiceDesc, srv)
}

func _SignalingService_DecideRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SpaceMember)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SignalingServiceServer).DecideRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/signaling.SignalingService/DecideRequest",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SignalingServiceServer).DecideRequest(ctx, req.(*SpaceMember))
	}
	return interceptor(ctx, in, info, handler)
}

func _SignalingService_BroadcastToLobby_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BroadcastRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SignalingServiceServer).BroadcastToLobby(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/signaling.SignalingService/BroadcastToLobby",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SignalingServiceServer).BroadcastToLobby(ctx, req.(*BroadcastRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SignalingService_Unicast_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnicastRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SignalingServiceServer).Unicast(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/signaling.SignalingService/Unicast",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SignalingServiceServer).Unicast(ctx, req.(*UnicastRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SignalingService_ServiceDesc is the grpc.ServiceDesc for SignalingService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SignalingService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "signaling.SignalingService",
	HandlerType: (*SignalingServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "DecideRequest",
			Handler:    _SignalingService_DecideRequest_Handler,
		},
		{
			MethodName: "BroadcastToLobby",
			Handler:    _SignalingService_BroadcastToLobby_Handler,
		},
		{
			MethodName: "Unicast",
			Handler:    _SignalingService_Unicast_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "signaling/signaling.proto",
}
