// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v6.33.2
// source: media/media.proto

package media

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// MediaServiceClient is the client API for MediaService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MediaServiceClient interface {
	GetRoom(ctx context.Context, in *GetRoomRequest, opts ...grpc.CallOption) (*GetRoomResponse, error)
	RemoveParticipant(ctx context.Context, in *RemoveParticipantRequest, opts ...grpc.CallOption) (*GetRoomResponse, error)
	CreatePeer(ctx context.Context, in *CreatePeerRequest, opts ...grpc.CallOption) (*GetRoomResponse, error)
	CreateViewerPeer(ctx context.Context, in *CreateViewerPeerRequest, opts ...grpc.CallOption) (*GetRoomResponse, error)
	AddCandidate(ctx context.Context, in *AddCandidateRequest, opts ...grpc.CallOption) (*Void, error)
	AddViewerCandidate(ctx context.Context, in *AddCandidateRequest, opts ...grpc.CallOption) (*Void, error)
	SetAnswer(ctx context.Context, in *SetAnswerRequest, opts ...grpc.CallOption) (*Void, error)
	SetViewerAnswer(ctx context.Context, in *SetAnswerRequest, opts ...grpc.CallOption) (*Void, error)
	ChangeMemberState(ctx context.Context, in *SpaceMemberRequest, opts ...grpc.CallOption) (*Void, error)
}

type mediaServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMediaServiceClient(cc grpc.ClientConnInterface) MediaServiceClient {
	return &mediaServiceClient{cc}
}

func (c *mediaServiceClient) GetRoom(ctx context.Context, in *GetRoomRequest, opts ...grpc.CallOption) (*GetRoomResponse, error) {
	out := new(GetRoomResponse)
	err := c.cc.Invoke(ctx, "/media.MediaService/GetRoom", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mediaServiceClient) RemoveParticipant(ctx context.Context, in *RemoveParticipantRequest, opts ...grpc.CallOption) (*GetRoomResponse, error) {
	out := new(GetRoomResponse)
	err := c.cc.Invoke(ctx, "/media.MediaService/RemoveParticipant", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mediaServiceClient) CreatePeer(ctx context.Context, in *CreatePeerRequest, opts ...grpc.CallOption) (*GetRoomResponse, error) {
	out := new(GetRoomResponse)
	err := c.cc.Invoke(ctx, "/media.MediaService/CreatePeer", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mediaServiceClient) CreateViewerPeer(ctx context.Context, in *CreateViewerPeerRequest, opts ...grpc.CallOption) (*GetRoomResponse, error) {
	out := new(GetRoomResponse)
	err := c.cc.Invoke(ctx, "/media.MediaService/CreateViewerPeer", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mediaServiceClient) AddCandidate(ctx context.Context, in *AddCandidateRequest, opts ...grpc.CallOption) (*Void, error) {
	out := new(Void)
	err := c.cc.Invoke(ctx, "/media.MediaService/AddCandidate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mediaServiceClient) AddViewerCandidate(ctx context.Context, in *AddCandidateRequest, opts ...grpc.CallOption) (*Void, error) {
	out := new(Void)
	err := c.cc.Invoke(ctx, "/media.MediaService/AddViewerCandidate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mediaServiceClient) SetAnswer(ctx context.Context, in *SetAnswerRequest, opts ...grpc.CallOption) (*Void, error) {
	out := new(Void)
	err := c.cc.Invoke(ctx, "/media.MediaService/SetAnswer", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mediaServiceClient) SetViewerAnswer(ctx context.Context, in *SetAnswerRequest, opts ...grpc.CallOption) (*Void, error) {
	out := new(Void)
	err := c.cc.Invoke(ctx, "/media.MediaService/SetViewerAnswer", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mediaServiceClient) ChangeMemberState(ctx context.Context, in *SpaceMemberRequest, opts ...grpc.CallOption) (*Void, error) {
	out := new(Void)
	err := c.cc.Invoke(ctx, "/media.MediaService/ChangeMemberState", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MediaServiceServer is the server API for MediaService service.
// All implementations must embed UnimplementedMediaServiceServer
// for forward compatibility
type MediaServiceServer interface {
	GetRoom(context.Context, *GetRoomRequest) (*GetRoomResponse, error)
	RemoveParticipant(context.Context, *RemoveParticipantRequest) (*GetRoomResponse, error)
	CreatePeer(context.Context, *CreatePeerRequest) (*GetRoomResponse, error)
	CreateViewerPeer(context.Context, *CreateViewerPeerRequest) (*GetRoomResponse, error)
	AddCandidate(context.Context, *AddCandidateRequest) (*Void, error)
	AddViewerCandidate(context.Context, *AddCandidateRequest) (*Void, error)
	SetAnswer(context.Context, *SetAnswerRequest) (*Void, error)
	SetViewerAnswer(context.Context, *SetAnswerRequest) (*Void, error)
	ChangeMemberState(context.Context, *SpaceMemberRequest) (*Void, error)
	mustEmbedUnimplementedMediaServiceServer()
}

// UnimplementedMediaServiceServer must be embedded to have forward compatible implementations.
type UnimplementedMediaServiceServer struct {
}

func (UnimplementedMediaServiceServer) GetRoom(context.Context, *GetRoomRequest) (*GetRoomResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRoom not implemented")
}
func (UnimplementedMediaServiceServer) RemoveParticipant(context.Context, *RemoveParticipantRequest) (*GetRoomResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RemoveParticipant not implemented")
}
func (UnimplementedMediaServiceServer) CreatePeer(context.Context, *CreatePeerRequest) (*GetRoomResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreatePeer not implemented")
}
func (UnimplementedMediaServiceServer) CreateViewerPeer(context.Context, *CreateViewerPeerRequest) (*GetRoomResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateViewerPeer not implemented")
}
func (UnimplementedMediaServiceServer) AddCandidate(context.Context, *AddCandidateRequest) (*Void, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddCandidate not implemented")
}
func (UnimplementedMediaServiceServer) AddViewerCandidate(context.Context, *AddCandidateRequest) (*Void, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddViewerCandidate not implemented")
}
func (UnimplementedMediaServiceServer) SetAnswer(context.Context, *SetAnswerRequest) (*Void, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetAnswer not implemented")
}
func (UnimplementedMediaServiceServer) SetViewerAnswer(context.Context, *SetAnswerRequest) (*Void, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetViewerAnswer not implemented")
}
func (UnimplementedMediaServiceServer) ChangeMemberState(context.Context, *SpaceMemberRequest) (*Void, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ChangeMemberState not implemented")
}
func (UnimplementedMediaServiceServer) mustEmbedUnimplementedMediaServiceServer() {}

// UnsafeMediaServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MediaServiceServer will
// result in compilation errors.
type UnsafeMediaServiceServer interface {
	mustEmbedUnimplementedMediaServiceServer()
}

func RegisterMediaServiceServer(s grpc.ServiceRegistrar, srv MediaServiceServer) {
	s.RegisterService(&MediaService_ServiceDesc, srv)
}

func _MediaService_GetRoom_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRoomRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MediaServiceServer).GetRoom(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/media.MediaService/GetRoom",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MediaServiceServer).GetRoom(ctx, req.(*GetRoomRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MediaService_RemoveParticipant_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveParticipantRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MediaServiceServer).RemoveParticipant(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/media.MediaService/RemoveParticipant",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MediaServiceServer).RemoveParticipant(ctx, req.(*RemoveParticipantRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MediaService_CreatePeer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreatePeerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MediaServiceServer).CreatePeer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/media.MediaService/CreatePeer",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MediaServiceServer).CreatePeer(ctx, req.(*CreatePeerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MediaService_CreateViewerPeer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateViewerPeerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MediaServiceServer).CreateViewerPeer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/media.MediaService/CreateViewerPeer",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MediaServiceServer).CreateViewerPeer(ctx, req.(*CreateViewerPeerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MediaService_AddCandidate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddCandidateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MediaServiceServer).AddCandidate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/media.MediaService/AddCandidate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MediaServiceServer).AddCandidate(ctx, req.(*AddCandidateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MediaService_AddViewerCandidate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddCandidateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MediaServiceServer).AddViewerCandidate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/media.MediaService/AddViewerCandidate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MediaServiceServer).AddViewerCandidate(ctx, req.(*AddCandidateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MediaService_SetAnswer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetAnswerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MediaServiceServer).SetAnswer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/media.MediaService/SetAnswer",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MediaServiceServer).SetAnswer(ctx, req.(*SetAnswerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MediaService_SetViewerAnswer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetAnswerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MediaServiceServer).SetViewerAnswer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/media.MediaService/SetViewerAnswer",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MediaServiceServer).SetViewerAnswer(ctx, req.(*SetAnswerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MediaService_ChangeMemberState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SpaceMemberRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MediaServiceServer).ChangeMemberState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/media.MediaService/ChangeMemberState",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MediaServiceServer).ChangeMemberState(ctx, req.(*SpaceMemberRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MediaService_ServiceDesc is the grpc.ServiceDesc for MediaService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MediaService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "media.MediaService",
	HandlerType: (*MediaServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetRoom",
			Handler:    _MediaService_GetRoom_Handler,
		},
		{
			MethodName: "RemoveParticipant",
			Handler:    _MediaService_RemoveParticipant_Handler,
		},
		{
			MethodName: "CreatePeer",
			Handler:    _MediaService_CreatePeer_Handler,
		},
		{
			MethodName: "CreateViewerPeer",
			Handler:    _MediaService_CreateViewerPeer_Handler,
		},
		{
			MethodName: "AddCandidate",
			Handler:    _MediaService_AddCandidate_Handler,
		},
		{
			MethodName: "AddViewerCandidate",
			Handler:    _MediaService_AddViewerCandidate_Handler,
		},
		{
			MethodName: "SetAnswer",
			Handler:    _MediaService_SetAnswer_Handler,
		},
		{
			MethodName: "SetViewerAnswer",
			Handler:    _MediaService_SetViewerAnswer_Handler,
		},
		{
			MethodName: "ChangeMemberState",
			Handler:    _MediaService_ChangeMemberState_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "media/media.proto",
}
